version: 0.0
os: windows
files:
  - source: \WebApp\
    destination: c:\inetpub\wwwroot\webtest
  
hooks:
  AfterInstall:
    - location: \installwebsite.bat
      timeout: 180
      runas: Administrator

